"""Cut Lumi's sprites from art/lumi/lumi-wave.png and art/lumi/lumi-lantern-idle.png.

    python3 scripts/cut-lumi-idle.py [--debug <dir>]

Writes public/lumi-idle.webp (the corner companion's body) and
public/lumi-heads.png (the chat avatar's six heads).

The body comes from the wave sheet (2026-09-13, generated by
scripts/gen-lumi-sheet.py from art/prompts/lumi-wave.md): 24 in-betweened
frames of one drawing in three rows of eight — rest, her free right hand (on
the viewer's left) rising beside the hood, two waves, the hand lowering, rest.
Its rows and cells are found by segmentation. Every loop is made from that one
drawing, so a hand-over between loops never swaps drawings:

- breath: the wave's first cell stretched up to 2px at the hood top with the
  feet held (cubic resample on premultiplied channels, anchored on the feet
  baseline), nine cells;
- wave: the 24 cells, each row scaled so she stands FIGURE_H tall, placed so
  the hood's right edge holds (the waving hand widens her on the left), then
  settled onto the first cell on the right half of the head — whole pixels,
  then a quarter pixel both ways;
- blink: half-shut and shut eyes on every breath cell, drawn by bringing a lid
  down over her own eyes (neither sheet has a blink row) — the lid is the
  face's own black, the bottom of each eye stays as a thin bright lens. The
  wave keeps its eyes open (a blink during a 3 s gesture goes unseen, and the
  extra rows tripled the sheet).

The heads come from six cells of the lantern sheet (sixteen drawings — a pose
set with expressions, not in-betweens): neutral (1), blink (1 with the eyes
shut), happy (6), curious (11, a glance to the side), excited (12, the lantern
raised), sleepy (7, lowered lids).

Matte: the ground is flood-filled from *outside* the figure (so the cream hood
is never eaten); on the contrasting grey-blue ground the 2px edge band is
de-matted against the ground, the shadow under the feet is read by its blue
cast and redrawn in the warm tone the cream sheets had, and the lantern's
light on the ground — a warm blend of the ground and an orange light — is
lifted off as a translucent warm glow, so on the paper she lights it a little.

Output: public/lumi-idle.webp is 24 columns × 4 rows of 160×208 cells: breath
(nine cells) with open / half-shut / shut eyes in rows 0–2, the wave (24
cells, eyes open) in row 3;
public/lumi-heads.png is one row of six 176px squares, the hood 172px wide with
its bottom on row 161 like the earlier cut.
"""
import os
import sys
import numpy as np
from PIL import Image
from scipy import ndimage as ndi

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'art', 'lumi', 'lumi-lantern-idle.png')
WAVE_SRC = os.path.join(ROOT, 'art', 'lumi', 'lumi-wave.png')
OUT_BODY = os.path.join(ROOT, 'public', 'lumi-idle.webp')
OUT_HEADS = os.path.join(ROOT, 'public', 'lumi-heads.png')
DEBUG = sys.argv[sys.argv.index('--debug') + 1] if '--debug' in sys.argv else None

W, H = 160, 208       # body cell (wider than the earlier 144: the lantern's light pools on the ground beside her)
FEET_Y = 200          # feet baseline inside the cell
FIGURE_H = 173        # hood top to feet, px — what the earlier breath rest frame stood at, so she keeps her size on the page
HEAD_SHARE = 0.45     # the top of her height that is hood and face
TOL = 45              # ground tolerance for the flood fill
GROUND_BOX = ((5, 25), (5, 25))
ROWS = ((151, 393), (444, 687))   # y-range of each row of the lantern sheet's cells (it also carries a title, numbers and notes)
COLS = 8
WAVE_FRAMES = 24
BODY_COLS = WAVE_FRAMES           # the widest loop
BREATH_FRAMES = 9
BREATH_RISE = 2.0     # px at the hood top, at the top of the breath
HEAD_CELL = 176
HEAD_W, HEAD_BOTTOM = 172, 161   # hood width and its bottom row inside the head cell
HEADS = [('neutral', (0, 0), 'open'), ('blink', (0, 0), 'shut'), ('happy', (0, 5), 'open'),
         ('curious', (1, 2), 'open'), ('excited', (1, 3), 'open'), ('sleepy', (0, 6), 'open')]
SHADOW_RGB = (228, 218, 204)   # the cream sheets' shadow tone
GLOW_RGB = (240, 190, 130)     # the light the ground pool is a blend of (ground → this)
GLOW_MAX = 0.55                # its alpha at the brightest


def runs(on, minlen):
    """Start and end of each run of True longer than `minlen`."""
    out, s = [], None
    for i, v in enumerate(on):
        if v and s is None: s = i
        if not v and s is not None: out.append((s, i)); s = None
    if s is not None: out.append((s, len(on)))
    return [r for r in out if r[1] - r[0] > minlen]


class Sheet:
    def __init__(self, path, ground_box):
        self.src = np.array(Image.open(path).convert('RGB')).astype(int)
        (y0, y1), (x0, x1) = ground_box
        self.paper = np.median(self.src[y0:y1, x0:x1].reshape(-1, 3), axis=0)
        self.d_all = np.abs(self.src - self.paper).sum(axis=2)
        self.lum = self.src.mean(axis=2)

    def rows(self):
        """y-ranges of the rows of figures, found by segmentation (for a sheet with nothing on it but the cells)."""
        return runs((self.d_all > 60).sum(axis=1) > 3, 60)

    def frames(self, y0, y1, expect):
        """Bounding boxes of the figures in one row of the sheet."""
        m = self.d_all[y0:y1] > 60
        out = []
        for a, b in runs(m.sum(axis=0) > 3, 40):
            rows = np.where(m[:, a:b].sum(axis=1) > 2)[0]
            out.append((a, b, rows[0] + y0, rows[-1] + y0))
        assert len(out) == expect, (y0, out)
        return out

    def cell(self, row, col):
        return self.frames(*ROWS[row], COLS)[col]

    def matte(self, bbox):
        """One figure as straight-alpha RGBA plus the mask of its main body."""
        x0, x1, y0, y1 = bbox
        X0, X1, Y0, Y1 = x0 - 8, x1 + 8, y0 - 8, y1 + 12
        rgb = self.src[Y0:Y1, X0:X1]
        d = self.d_all[Y0:Y1, X0:X1]
        l = self.lum[Y0:Y1, X0:X1]
        chroma = rgb.max(axis=2) - rgb.min(axis=2)
        ground_l = self.paper.mean()

        def flood(cand):
            lab, n = ndi.label(cand)
            border = set(np.unique(np.concatenate([lab[0], lab[-1], lab[:, 0], lab[:, -1]])))
            border.discard(0)
            inside = ~np.isin(lab, list(border))
            il, k = ndi.label(inside)
            sizes = ndi.sum(inside, il, range(1, k + 1))
            return inside, il == (1 + int(np.argmax(sizes)))

        cand = d < TOL
        inside, main = flood(cand)
        feet = np.where(main.any(axis=1))[0].max()
        below = np.zeros_like(cand); below[feet - 14:] = True
        # The soft shadow is the ground darkened, so it keeps the ground's blue
        # cast (b > r); the lantern's pool of light is the ground warmed (r > b)
        # and brighter. Both are ground for the flood — otherwise they land
        # inside the figure, opaque — and are drawn back below.
        shadow = below & (rgb[:, :, 2] > rgb[:, :, 0]) & (chroma < 40) & (l < ground_l) & (d < 170)
        glow = below & (rgb[:, :, 0] > rgb[:, :, 2] + 12) & (l > ground_l + 3) & (l < 200)
        inside, main = flood(cand | shadow | glow)
        outside = ~inside
        alpha = np.where(inside, 255.0, 0.0)
        # shadow, in one warm tone whatever the sheet's ground
        dark = np.clip((ground_l - l) - 6, 0, None) * 4.5
        sh = outside & below & (chroma < 40) & (dark > 0)
        alpha = np.where(sh, np.clip(dark, 0, 170), alpha)
        rgb = np.where(sh[:, :, None], SHADOW_RGB, rgb)
        # the lantern's light on the ground, as a translucent warm glow
        gl = outside & glow & ~sh
        a_glow = np.clip((l - ground_l) / 110, 0, GLOW_MAX)
        alpha = np.where(gl, a_glow * 255, alpha)
        rgb = np.where(gl[:, :, None], GLOW_RGB, rgb)
        # De-matte the 2px edge band against the known ground — otherwise the
        # anti-aliased edge keeps a grey-blue fringe. Each edge pixel's own
        # colour is taken to be that of the nearest interior pixel, so its
        # coverage is how far it has moved from ground toward that.
        interior = ndi.binary_erosion(inside, iterations=2)
        band = inside & ~interior
        iy, ix = ndi.distance_transform_edt(~interior, return_indices=True)[1]
        own = rgb[iy, ix]
        full = np.maximum(np.abs(own - self.paper).sum(axis=2), 1)
        a = np.clip(d / full, 0, 1)[:, :, None]
        clean = np.clip((rgb - (1 - a) * self.paper) / np.maximum(a, 0.05), 0, 255)
        rgb = np.where(band[:, :, None], clean, rgb)
        alpha = np.where(band, a[:, :, 0] * 255, alpha)
        return np.dstack([rgb, alpha]).astype(np.uint8), main


def premul(c):
    a = c[:, :, 3:4].astype(float) / 255
    return np.dstack([c[:, :, :3] * a, c[:, :, 3:4].astype(float)])


def straight(p):
    a = np.clip(p[:, :, 3:4], 0, 255)
    return np.dstack([np.clip(p[:, :, :3] / np.maximum(a / 255, 1e-3), 0, 255), a]).astype(np.uint8)


def scale(rgba, main, s):
    """Resize on premultiplied alpha, so the edge doesn't pick up a dark halo from the transparent black outside."""
    if s == 1: return rgba, main
    h, w = rgba.shape[:2]
    size = (int(round(w * s)), int(round(h * s)))
    pre = premul(rgba).astype(np.float32)
    out = np.dstack([np.array(Image.fromarray(pre[:, :, i]).resize(size, Image.LANCZOS)) for i in range(4)])
    main = np.array(Image.fromarray(main.astype(np.uint8) * 255, 'L').resize(size, Image.BILINEAR)) > 127
    return straight(out), main


def place(rgba, main, w, h, feet_y, cx=None):
    """Paste into a w×h cell with the main body's feet on `feet_y` and the body (or `cx`) centred."""
    cell = np.zeros((h, w, 4), dtype=np.uint8)
    ys, xs = np.where(main)
    if cx is None: cx = (xs.min() + xs.max()) / 2
    ox = int(round(w / 2 - cx)); oy = feet_y - ys.max()
    hh, ww = rgba.shape[:2]
    sy0, sx0 = max(0, -oy), max(0, -ox)
    ty0, tx0 = max(0, oy), max(0, ox)
    hh, ww = min(hh - sy0, h - ty0), min(ww - sx0, w - tx0)
    cell[ty0:ty0 + hh, tx0:tx0 + ww] = rgba[sy0:sy0 + hh, sx0:sx0 + ww]
    return cell


def hood_right(main):
    """Right edge of the hood: it holds while her free hand, on the left, comes up beside the hood."""
    ys = np.where(main.any(axis=1))[0]
    head = main[ys.min():ys.min() + int((ys.max() - ys.min()) * HEAD_SHARE)]
    return np.where(head.any(axis=0))[0].max()


def shift(cell, dx, dy):
    """The cell moved by a fractional (dx, dy): cubic resampling on premultiplied channels."""
    pre = premul(cell)
    return straight(np.dstack([ndi.shift(pre[:, :, i], (dy, dx), order=3, mode='constant') for i in range(4)]))


def settle(cell, ref, col0, head_rows, reach=4, fine=1.0, step=0.25):
    """Move `cell` so the right half of its head (rows above `head_rows`, columns from `col0`) best
    overlaps `ref`'s: whole pixels sideways, then a quarter pixel both ways (a frame half a pixel off
    its neighbour doubles the hood's edge under the crossfade). The right half only, because the
    waving hand comes up beside the hood's left side. Returns the cell and the overlap reached."""
    def region(alpha):
        a = alpha.copy(); a[head_rows:] = 0; a[:, :col0] = 0
        return a
    iou = lambda s, r: np.minimum(s, r).sum() / np.maximum(s, r).sum()
    r = region(ref[:, :, 3].astype(float) / 255)
    a = cell[:, :, 3].astype(float) / 255
    dx = max(range(-reach, reach + 1), key=lambda d: iou(region(np.roll(a, d, axis=1)), r))
    a = np.roll(a, dx, axis=1)
    steps = np.arange(-fine, fine + step / 2, step)
    fx, fy = max(((fx, fy) for fx in steps for fy in steps), key=lambda p: iou(region(ndi.shift(a, (p[1], p[0]), order=1)), r))
    best = iou(region(ndi.shift(a, (fy, fx), order=1)), r)
    return shift(cell, dx + fx, fy), best


def face(cell):
    """Mask of the dark face (holes filled, so the eyes are inside it) and of its dark pixels alone."""
    dark = (cell[:, :, :3].sum(axis=2) < 150) & (cell[:, :, 3] > 200)
    filled = ndi.binary_fill_holes(dark)
    fl, k = ndi.label(filled)
    sizes = ndi.sum(filled, fl, range(1, k + 1))
    return fl == (1 + int(np.argmax(sizes))), dark


def eyes_shut(cell, keep):
    """The cell with a lid drawn down over each eye, leaving the bottom `keep` of it
    (0.5 half-shut, 0.2 shut). The lid is the face's own black; the row it
    stops on is blended half and half, so the lid edge is not a jagged line."""
    filled, dark = face(cell)
    eyes = filled & ~dark
    lab, k = ndi.label(eyes)
    sizes = ndi.sum(eyes, lab, range(1, k + 1))
    # the two largest *bright* holes: when the waving hand touches the face, a gap
    # between them is a hole too, and it is not an eye
    lit = [i for i in np.argsort(sizes)[::-1] if cell[lab == i + 1][:, 0].mean() > 180][:2]
    black = np.median(cell[dark][:, :3], axis=0)
    out = cell.copy().astype(float)
    for i in lit:
        eye = lab == i + 1
        ys = np.where(eye.any(axis=1))[0]
        lid = ys.min() + (ys.max() - ys.min() + 1) * (1 - keep)
        row = int(np.floor(lid)); part = lid - row
        cover = eye.copy(); cover[row:] = False
        lens = eye & ~cover
        # The eye lights the face around it a little; covered, that halo would
        # read as a ring, so the lid takes the halo with it (a few px around
        # the covered part, but not around the lens that stays lit).
        halo = ndi.binary_dilation(cover, iterations=5) & filled & ~ndi.binary_dilation(lens, iterations=3)
        out[halo, :3] = black
        edge = eye.copy(); edge[:row] = False; edge[row + 1:] = False
        out[edge, :3] = (1 - part) * out[edge, :3] + part * black
    return out.astype(np.uint8)


def breathe(cell, rise):
    """The cell stretched `rise` px taller at the hood top with the feet held — cubic resample on premultiplied channels."""
    if rise == 0: return cell
    sy = 1 + rise / FIGURE_H
    pre = premul(cell)
    out = np.dstack([ndi.affine_transform(pre[:, :, i], [1 / sy, 1], offset=[FEET_Y * (1 - 1 / sy), 0],
                                          output_shape=(H, W), order=3, mode='constant') for i in range(4)])
    return straight(out)


def head_cell(rgba, main, eyes):
    """The hood and face cut under the chin (above the ribbon), the hood HEAD_W wide with its bottom on HEAD_BOTTOM."""
    if eyes == 'shut': rgba = eyes_shut(rgba, 0.2)
    ys = np.where(main.any(axis=1))[0]
    top, h = ys.min(), ys.max() - ys.min()
    cut = top + int(round(h * 0.53))   # the chin's point sits at ~0.49 of her height; the hood's rim wraps a little under it
    rgba, main = rgba[:cut].copy(), main[:cut].copy()
    fade = np.linspace(0.3, 1, 4)[:, None]        # the last rows soften rather than end on a hard line
    rgba[-4:, :, 3] = (rgba[-4:, :, 3] * fade).astype(np.uint8)
    xs = np.where(main.any(axis=0))[0]
    rgba, main = scale(rgba, main, HEAD_W / (xs.max() - xs.min() + 1))
    return place(rgba, main, HEAD_CELL, HEAD_CELL, HEAD_BOTTOM)


# The wave: every cell matted, each row scaled so she stands FIGURE_H tall.
wave_sheet = Sheet(WAVE_SRC, GROUND_BOX)
boxes = [(r, b) for r, (y0, y1) in enumerate(wave_sheet.rows()) for b in wave_sheet.frames(y0, y1, COLS)]
assert len(boxes) == WAVE_FRAMES, len(boxes)
matted = [(r, *wave_sheet.matte(b)) for r, b in boxes]
height = lambda main: np.ptp(np.where(main.any(axis=1))[0])
row_scale = {r: FIGURE_H / np.median([height(m) for rr, _, m in matted if rr == r]) for r in sorted({r for r, _, _ in matted})}
print('wave row scales', {r: round(float(s), 3) for r, s in row_scale.items()})
scaled = [scale(rgba, main, row_scale[r]) for r, rgba, main in matted]
# Placed so the hood's right edge sits where the first cell's does (that cell centred with her lantern),
# then settled onto the first cell.
xs = np.where(scaled[0][1].any(axis=0))[0]
anchor = hood_right(scaled[0][1]) - (xs.min() + xs.max()) / 2
wave = [place(rgba, main, W, H, FEET_Y, cx=hood_right(main) - anchor) for rgba, main in scaled]
rest = wave[0]
head_rows = FEET_Y - FIGURE_H + int(FIGURE_H * HEAD_SHARE)
hx = np.where((rest[:head_rows, :, 3] > 127).any(axis=0))[0]
col0 = int((hx.min() + hx.max()) / 2)
settled = [settle(c, rest, col0, head_rows) for c in wave[1:]]
wave[1:] = [c for c, _ in settled]
print('wave head overlap with the first cell after settling (right half):', [round(float(o), 3) for _, o in settled])

# The breath: the wave's first cell, stretched, so the two loops are one drawing.
rises = [BREATH_RISE * (1 - np.cos(2 * np.pi * i / BREATH_FRAMES)) / 2 for i in range(BREATH_FRAMES)]
print('breath rise per frame, px:', [round(r, 2) for r in rises])
KEEP = [None, 0.5, 0.2]   # open, half-shut, shut
lids = lambda cell, keep: cell if keep is None else eyes_shut(cell, keep)
# The wave keeps its eyes open: a blink during a 3 s gesture goes unseen, and its half-shut and shut
# rows would have tripled the sheet (917 KB against 244 KB before the wave). LumiSprite's
# LUMI_LOOP_EYES says which eye rows each loop has.
eye_rows = [
    [[breathe(lids(rest, keep), rise) for rise in rises] for keep in KEEP],
    [wave],
]
body = np.zeros((H * sum(len(rows) for rows in eye_rows), W * BODY_COLS, 4), dtype=np.uint8)
for r, cells in enumerate(row for rows in eye_rows for row in rows):
    for c, cell in enumerate(cells):
        body[r * H:(r + 1) * H, c * W:(c + 1) * W] = cell
Image.fromarray(body, 'RGBA').save(OUT_BODY, quality=90, method=6)
print('wrote', OUT_BODY, body.shape[1], 'x', body.shape[0], os.path.getsize(OUT_BODY), 'bytes')

sheet = Sheet(SRC, GROUND_BOX)
heads = np.zeros((HEAD_CELL, HEAD_CELL * len(HEADS), 4), dtype=np.uint8)
for i, (name, at, eyes) in enumerate(HEADS):
    heads[:, i * HEAD_CELL:(i + 1) * HEAD_CELL] = head_cell(*sheet.matte(sheet.cell(*at)), eyes)
Image.fromarray(heads, 'RGBA').save(OUT_HEADS, optimize=True)
print('wrote', OUT_HEADS, heads.shape[1], 'x', heads.shape[0], os.path.getsize(OUT_HEADS), 'bytes')

if DEBUG:
    # Everything on the app's paper, to look at: the heads at 3×, the body at 1× (it is 3840 wide).
    paper = (246, 241, 232)
    def on_paper(a, k=3):
        im = Image.new('RGBA', (a.shape[1], a.shape[0]), paper + (255,))
        im.alpha_composite(Image.fromarray(a, 'RGBA'))
        return im.resize((im.width * k, im.height * k), Image.NEAREST)
    on_paper(body, 1).save(os.path.join(DEBUG, 'cut-body.png'))
    on_paper(heads).save(os.path.join(DEBUG, 'cut-heads.png'))
    print('debug strips in', DEBUG)
