"""Cut Lumi's sprites from art/lumi/lumi-wave.png, art/lumi/lumi-foot-play.png and art/lumi/lumi-lantern-idle.png.

    python3 scripts/cut-lumi-idle.py [--debug <dir>]

Writes public/lumi-idle.webp (the corner companion's body) and
public/lumi-heads.png (the chat avatar's six heads).

The body comes from the wave sheet (2026-09-13, generated by
scripts/gen-lumi-sheet.py from art/prompts/lumi-wave.md): 24 in-betweened
frames of one drawing in three rows of eight — rest, her free right hand (on
the viewer's left) rising beside the hood, two waves, the hand lowering, rest.
Its rows and cells are found by segmentation. Every loop is made from that one
drawing, so a hand-over between loops never swaps drawings:

- breath: the wave's first cell stretched up to 2px at the hood top with the
  feet held (cubic resample on premultiplied channels, anchored on the feet
  baseline), nine cells;
- wave: the 24 cells, each row scaled so she stands FIGURE_H tall, placed by
  the hood's right edge (the waving hand widens her on the left), aligned on
  the first cell over the parts that hold — the hood's right half, the lantern
  side, the boots — within 6px both ways and then to a quarter pixel, and then
  held: everything but the arm and the cloak it moves is the first cell's, so
  the hood, eyes, lantern and boots never move (Chanté: "she jumps around a
  little bit" — five cells had dropped 2–4px and the rest drifted a pixel);
  then held again per phase: the rest cells are the first cell exactly, the
  waves keep one cell's arm and cloak with only the hand and wrist swinging,
  and the lower cloak only lifts through the rise and only drops through the
  fall (the redraw bobbed the hem: "still jittering a bit, mostly up and down");
- blink: half-shut and shut eyes on every breath cell, drawn by bringing a lid
  down over her own eyes (neither sheet has a blink row) — the lid is the
  face's own black, the bottom of each eye stays as a thin bright lens. The
  wave keeps its eyes open (a blink during a 3 s gesture goes unseen, and the
  extra rows tripled the sheet).

The heads come from six cells of the lantern sheet (sixteen drawings — a pose
set with expressions, not in-betweens): neutral (1), blink (1 with the eyes
shut), happy (6), curious (11, a glance to the side), excited (12, the lantern
raised), sleepy (7, lowered lids).

Matte: the ground is flood-filled from *outside* the figure (so the cream hood
is never eaten); on the contrasting grey-blue ground the 2px edge band is
de-matted against the ground, the shadow under the feet is read by its blue
cast and redrawn in the warm tone the cream sheets had, and the lantern's
light on the ground — a warm blend of the ground and an orange light — is
lifted off as a translucent warm glow, so on the paper she lights it a little.

The foot play (2026-09-13, from art/lumi/lumi-foot-play.png, generated from
art/prompts/lumi-foot-play.md) is another generation of the same drawing, so
only two parts are taken from it onto the wave's first cell: the eyes (lowered
to the ground and held, one cell's eyes through the held phase) and her right
boot (on the viewer's left) where it lifts and scuffs. Its cells are aligned on
the whole hood, the lantern side and the other boot first; everything else is
`rest`, so it hands over like the wave. LumiSprite plays the row four ways.

Output: public/lumi-idle.webp is 24 columns × 5 rows of 160×208 cells: breath
(nine cells) with open / half-shut / shut eyes in rows 0–2, the wave (24
cells, eyes open) in row 3, the foot play (24 cells, eyes open) in row 4;
public/lumi-heads.png is one row of six 176px squares, the hood 172px wide with
its bottom on row 161 like the earlier cut.
"""
import os
import sys
import numpy as np
from PIL import Image
from scipy import ndimage as ndi

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'art', 'lumi', 'lumi-lantern-idle.png')
WAVE_SRC = os.path.join(ROOT, 'art', 'lumi', 'lumi-wave.png')
OUT_BODY = os.path.join(ROOT, 'public', 'lumi-idle.webp')
OUT_HEADS = os.path.join(ROOT, 'public', 'lumi-heads.png')
DEBUG = sys.argv[sys.argv.index('--debug') + 1] if '--debug' in sys.argv else None

W, H = 160, 208       # body cell (wider than the earlier 144: the lantern's light pools on the ground beside her)
FEET_Y = 200          # feet baseline inside the cell
FIGURE_H = 173        # hood top to feet, px — what the earlier breath rest frame stood at, so she keeps her size on the page
HEAD_SHARE = 0.45     # the top of her height that is hood and face
TOL = 45              # ground tolerance for the flood fill
GROUND_BOX = ((5, 25), (5, 25))
ROWS = ((151, 393), (444, 687))   # y-range of each row of the lantern sheet's cells (it also carries a title, numbers and notes)
COLS = 8
WAVE_FRAMES = 24
BODY_COLS = WAVE_FRAMES           # the widest loop
BREATH_FRAMES = 9
BREATH_RISE = 2.0     # px at the hood top, at the top of the breath
HEAD_CELL = 176
HEAD_W, HEAD_BOTTOM = 172, 161   # hood width and its bottom row inside the head cell
HEADS = [('neutral', (0, 0), 'open'), ('blink', (0, 0), 'shut'), ('happy', (0, 5), 'open'),
         ('curious', (1, 2), 'open'), ('excited', (1, 3), 'open'), ('sleepy', (0, 6), 'open')]
SHADOW_RGB = (228, 218, 204)   # the cream sheets' shadow tone
GLOW_RGB = (240, 190, 130)     # the light the ground pool is a blend of (ground → this)
GLOW_MAX = 0.55                # its alpha at the brightest


def runs(on, minlen):
    """Start and end of each run of True longer than `minlen`."""
    out, s = [], None
    for i, v in enumerate(on):
        if v and s is None: s = i
        if not v and s is not None: out.append((s, i)); s = None
    if s is not None: out.append((s, len(on)))
    return [r for r in out if r[1] - r[0] > minlen]


class Sheet:
    def __init__(self, path, ground_box):
        self.src = np.array(Image.open(path).convert('RGB')).astype(int)
        (y0, y1), (x0, x1) = ground_box
        self.paper = np.median(self.src[y0:y1, x0:x1].reshape(-1, 3), axis=0)
        self.d_all = np.abs(self.src - self.paper).sum(axis=2)
        self.lum = self.src.mean(axis=2)

    def rows(self):
        """y-ranges of the rows of figures, found by segmentation (for a sheet with nothing on it but the cells)."""
        return runs((self.d_all > 60).sum(axis=1) > 3, 60)

    def frames(self, y0, y1, expect):
        """Bounding boxes of the figures in one row of the sheet."""
        m = self.d_all[y0:y1] > 60
        out = []
        for a, b in runs(m.sum(axis=0) > 3, 40):
            rows = np.where(m[:, a:b].sum(axis=1) > 2)[0]
            out.append((a, b, rows[0] + y0, rows[-1] + y0))
        assert len(out) == expect, (y0, out)
        return out

    def cell(self, row, col):
        return self.frames(*ROWS[row], COLS)[col]

    def matte(self, bbox):
        """One figure as straight-alpha RGBA plus the mask of its main body."""
        x0, x1, y0, y1 = bbox
        X0, X1, Y0, Y1 = x0 - 8, x1 + 8, y0 - 8, y1 + 12
        rgb = self.src[Y0:Y1, X0:X1]
        d = self.d_all[Y0:Y1, X0:X1]
        l = self.lum[Y0:Y1, X0:X1]
        chroma = rgb.max(axis=2) - rgb.min(axis=2)
        ground_l = self.paper.mean()

        def flood(cand):
            lab, n = ndi.label(cand)
            border = set(np.unique(np.concatenate([lab[0], lab[-1], lab[:, 0], lab[:, -1]])))
            border.discard(0)
            inside = ~np.isin(lab, list(border))
            il, k = ndi.label(inside)
            sizes = ndi.sum(inside, il, range(1, k + 1))
            return inside, il == (1 + int(np.argmax(sizes)))

        cand = d < TOL
        inside, main = flood(cand)
        feet = np.where(main.any(axis=1))[0].max()
        below = np.zeros_like(cand); below[feet - 14:] = True
        # The soft shadow is the ground darkened, so it keeps the ground's blue
        # cast (b > r); the lantern's pool of light is the ground warmed (r > b)
        # and brighter. Both are ground for the flood — otherwise they land
        # inside the figure, opaque — and are drawn back below.
        shadow = below & (rgb[:, :, 2] > rgb[:, :, 0]) & (chroma < 40) & (l < ground_l) & (d < 170)
        glow = below & (rgb[:, :, 0] > rgb[:, :, 2] + 12) & (l > ground_l + 3) & (l < 200)
        inside, main = flood(cand | shadow | glow)
        outside = ~inside
        alpha = np.where(inside, 255.0, 0.0)
        # shadow, in one warm tone whatever the sheet's ground
        dark = np.clip((ground_l - l) - 6, 0, None) * 4.5
        sh = outside & below & (chroma < 40) & (dark > 0)
        alpha = np.where(sh, np.clip(dark, 0, 170), alpha)
        rgb = np.where(sh[:, :, None], SHADOW_RGB, rgb)
        # the lantern's light on the ground, as a translucent warm glow
        gl = outside & glow & ~sh
        a_glow = np.clip((l - ground_l) / 110, 0, GLOW_MAX)
        alpha = np.where(gl, a_glow * 255, alpha)
        rgb = np.where(gl[:, :, None], GLOW_RGB, rgb)
        # De-matte the 2px edge band against the known ground — otherwise the
        # anti-aliased edge keeps a grey-blue fringe. Each edge pixel's own
        # colour is taken to be that of the nearest interior pixel, so its
        # coverage is how far it has moved from ground toward that.
        interior = ndi.binary_erosion(inside, iterations=2)
        band = inside & ~interior
        iy, ix = ndi.distance_transform_edt(~interior, return_indices=True)[1]
        own = rgb[iy, ix]
        full = np.maximum(np.abs(own - self.paper).sum(axis=2), 1)
        a = np.clip(d / full, 0, 1)[:, :, None]
        clean = np.clip((rgb - (1 - a) * self.paper) / np.maximum(a, 0.05), 0, 255)
        rgb = np.where(band[:, :, None], clean, rgb)
        alpha = np.where(band, a[:, :, 0] * 255, alpha)
        return np.dstack([rgb, alpha]).astype(np.uint8), main


def premul(c):
    a = c[:, :, 3:4].astype(float) / 255
    return np.dstack([c[:, :, :3] * a, c[:, :, 3:4].astype(float)])


def straight(p):
    a = np.clip(p[:, :, 3:4], 0, 255)
    return np.dstack([np.clip(p[:, :, :3] / np.maximum(a / 255, 1e-3), 0, 255), a]).astype(np.uint8)


def scale(rgba, main, s):
    """Resize on premultiplied alpha, so the edge doesn't pick up a dark halo from the transparent black outside."""
    if s == 1: return rgba, main
    h, w = rgba.shape[:2]
    size = (int(round(w * s)), int(round(h * s)))
    pre = premul(rgba).astype(np.float32)
    out = np.dstack([np.array(Image.fromarray(pre[:, :, i]).resize(size, Image.LANCZOS)) for i in range(4)])
    main = np.array(Image.fromarray(main.astype(np.uint8) * 255, 'L').resize(size, Image.BILINEAR)) > 127
    return straight(out), main


def place(rgba, main, w, h, feet_y, cx=None):
    """Paste into a w×h cell with the main body's feet on `feet_y` and the body (or `cx`) centred."""
    cell = np.zeros((h, w, 4), dtype=np.uint8)
    ys, xs = np.where(main)
    if cx is None: cx = (xs.min() + xs.max()) / 2
    ox = int(round(w / 2 - cx)); oy = feet_y - ys.max()
    hh, ww = rgba.shape[:2]
    sy0, sx0 = max(0, -oy), max(0, -ox)
    ty0, tx0 = max(0, oy), max(0, ox)
    hh, ww = min(hh - sy0, h - ty0), min(ww - sx0, w - tx0)
    cell[ty0:ty0 + hh, tx0:tx0 + ww] = rgba[sy0:sy0 + hh, sx0:sx0 + ww]
    return cell


def hood_right(main):
    """Right edge of the hood: it holds while her free hand, on the left, comes up beside the hood."""
    ys = np.where(main.any(axis=1))[0]
    head = main[ys.min():ys.min() + int((ys.max() - ys.min()) * HEAD_SHARE)]
    return np.where(head.any(axis=0))[0].max()


def shift(cell, dx, dy):
    """The cell moved by a fractional (dx, dy): cubic resampling on premultiplied channels."""
    pre = premul(cell)
    return straight(np.dstack([ndi.shift(pre[:, :, i], (dy, dx), order=3, mode='constant') for i in range(4)]))


def face(cell):
    """Mask of the dark face (holes filled, so the eyes are inside it) and of its dark pixels alone."""
    dark = (cell[:, :, :3].sum(axis=2) < 150) & (cell[:, :, 3] > 200)
    filled = ndi.binary_fill_holes(dark)
    fl, k = ndi.label(filled)
    sizes = ndi.sum(filled, fl, range(1, k + 1))
    return fl == (1 + int(np.argmax(sizes))), dark


def eyes_shut(cell, keep):
    """The cell with a lid drawn down over each eye, leaving the bottom `keep` of it
    (0.5 half-shut, 0.2 shut). The lid is the face's own black; the row it
    stops on is blended half and half, so the lid edge is not a jagged line."""
    filled, dark = face(cell)
    eyes = filled & ~dark
    lab, k = ndi.label(eyes)
    sizes = ndi.sum(eyes, lab, range(1, k + 1))
    # the two largest *bright* holes: when the waving hand touches the face, a gap
    # between them is a hole too, and it is not an eye
    lit = [i for i in np.argsort(sizes)[::-1] if cell[lab == i + 1][:, 0].mean() > 180][:2]
    black = np.median(cell[dark][:, :3], axis=0)
    out = cell.copy().astype(float)
    for i in lit:
        eye = lab == i + 1
        ys = np.where(eye.any(axis=1))[0]
        lid = ys.min() + (ys.max() - ys.min() + 1) * (1 - keep)
        row = int(np.floor(lid)); part = lid - row
        cover = eye.copy(); cover[row:] = False
        lens = eye & ~cover
        # The eye lights the face around it a little; covered, that halo would
        # read as a ring, so the lid takes the halo with it (a few px around
        # the covered part, but not around the lens that stays lit).
        halo = ndi.binary_dilation(cover, iterations=5) & filled & ~ndi.binary_dilation(lens, iterations=3)
        out[halo, :3] = black
        edge = eye.copy(); edge[:row] = False; edge[row + 1:] = False
        out[edge, :3] = (1 - part) * out[edge, :3] + part * black
    return out.astype(np.uint8)


def breathe(cell, rise):
    """The cell stretched `rise` px taller at the hood top with the feet held — cubic resample on premultiplied channels."""
    if rise == 0: return cell
    sy = 1 + rise / FIGURE_H
    pre = premul(cell)
    out = np.dstack([ndi.affine_transform(pre[:, :, i], [1 / sy, 1], offset=[FEET_Y * (1 - 1 / sy), 0],
                                          output_shape=(H, W), order=3, mode='constant') for i in range(4)])
    return straight(out)


def head_cell(rgba, main, eyes):
    """The hood and face cut under the chin (above the ribbon), the hood HEAD_W wide with its bottom on HEAD_BOTTOM."""
    if eyes == 'shut': rgba = eyes_shut(rgba, 0.2)
    ys = np.where(main.any(axis=1))[0]
    top, h = ys.min(), ys.max() - ys.min()
    cut = top + int(round(h * 0.53))   # the chin's point sits at ~0.49 of her height; the hood's rim wraps a little under it
    rgba, main = rgba[:cut].copy(), main[:cut].copy()
    fade = np.linspace(0.3, 1, 4)[:, None]        # the last rows soften rather than end on a hard line
    rgba[-4:, :, 3] = (rgba[-4:, :, 3] * fade).astype(np.uint8)
    xs = np.where(main.any(axis=0))[0]
    rgba, main = scale(rgba, main, HEAD_W / (xs.max() - xs.min() + 1))
    return place(rgba, main, HEAD_CELL, HEAD_CELL, HEAD_BOTTOM)


# The wave: every cell matted, each row scaled so she stands FIGURE_H tall.
wave_sheet = Sheet(WAVE_SRC, GROUND_BOX)
boxes = [(r, b) for r, (y0, y1) in enumerate(wave_sheet.rows()) for b in wave_sheet.frames(y0, y1, COLS)]
assert len(boxes) == WAVE_FRAMES, len(boxes)
matted = [(r, *wave_sheet.matte(b)) for r, b in boxes]
height = lambda main: np.ptp(np.where(main.any(axis=1))[0])
row_scale = {r: FIGURE_H / np.median([height(m) for rr, _, m in matted if rr == r]) for r in sorted({r for r, _, _ in matted})}
print('wave row scales', {r: round(float(s), 3) for r, s in row_scale.items()})
scaled = [scale(rgba, main, row_scale[r]) for r, rgba, main in matted]
# Placed so the hood's right edge sits where the first cell's does (that cell centred with her lantern),
# then settled onto the first cell.
xs = np.where(scaled[0][1].any(axis=0))[0]
anchor = hood_right(scaled[0][1]) - (xs.min() + xs.max()) / 2
wave = [place(rgba, main, W, H, FEET_Y, cx=hood_right(main) - anchor) for rgba, main in scaled]
rest = wave[0]
head_rows = FEET_Y - FIGURE_H + int(FIGURE_H * HEAD_SHARE)
hx = np.where((rest[:head_rows, :, 3] > 127).any(axis=0))[0]
col0 = int((hx.min() + hx.max()) / 2)
rest_face, _ = face(rest)
face_left = int(np.where(rest_face[:head_rows].any(axis=0))[0].min())


def align(cell, ref, held, reach=6, fine=1.0, step=0.25):
    """Move `cell` so its coverage best matches `ref`'s over `held` (weights on the parts that hold still):
    whole pixels both ways within `reach`, then a quarter pixel. Placing by the matte's lowest row dropped
    five cells 2–4px, feet and all, and settling on the head alone could not see it. Returns the cell and the overlap."""
    r = ref[:, :, 3].astype(float) / 255 * held
    score = lambda a: np.minimum(a * held, r).sum() / np.maximum(a * held, r).sum()
    a = cell[:, :, 3].astype(float) / 255
    dx, dy = max(((dx, dy) for dx in range(-reach, reach + 1) for dy in range(-reach, reach + 1)),
                 key=lambda d: score(np.roll(np.roll(a, d[1], axis=0), d[0], axis=1)))
    a = np.roll(np.roll(a, dy, axis=0), dx, axis=1)
    steps = np.arange(-fine, fine + step / 2, step)
    fx, fy = max(((fx, fy) for fx in steps for fy in steps), key=lambda p: score(ndi.shift(a, (p[1], p[0]), order=1)))
    return shift(cell, dx + fx, dy + fy), score(ndi.shift(a, (fy, fx), order=1))


def hold(cell, ref):
    """An animation hold: everything but what moves comes from `ref`. What moves is where the cell differs from
    `ref` in blobs, not lines (an opening drops the 1–2px outlines a redraw shifts), on her free side only — left of
    the hood's centre, and in the head rows left of the face, so the eyes, the hood, the lantern and the boots are
    `ref`'s in every frame — dilated a little and feathered, on premultiplied channels."""
    pc, pr = premul(cell), premul(ref)
    moving = np.abs(pc - pr).sum(axis=2) > 90
    moving[:, col0:] = False
    moving[:head_rows, face_left - 2:] = False
    moving[FEET_Y - 8:] = False
    moving = ndi.binary_fill_holes(ndi.binary_dilation(ndi.binary_opening(moving, iterations=2), iterations=3))
    w = ndi.gaussian_filter(moving.astype(float), 1.5)[:, :, None]
    return straight(w * pc + (1 - w) * pr)


held = np.zeros((H, W))
held[:head_rows, col0:] = 1        # the hood and face, right half
held[head_rows:, col0:] = 1        # the ribbon's right side and the lantern
held[FEET_Y - 10:, :] = 1          # the boots
aligned = [align(c, rest, held) for c in wave[1:]]
wave[1:] = [hold(c, rest) for c, _ in aligned]
print('wave overlap with the first cell on the held parts, after aligning:', [round(float(o), 3) for _, o in aligned])

WAVE_REST = [0, 1, 22, 23]        # cells that are the rest pose: exactly the first cell
WAVE_WAVES = range(8, 16)         # the two waves: the arm held up, only the hand and wrist swing
HAND_ROWS = 135                   # the raised hand never comes below this row of the cell


def hold_hand(cell, donor):
    """A hold inside a phase: while she waves, everything but the hand and wrist is `donor`'s. With the whole
    free side taken from each cell, the generator's redraw of the cloak bounced the left hem 1–2px frame to frame
    and the hood's tip by up to 1.5px (Chanté: "still jittering a bit, mostly up and down"). The hand is where the
    cell and the donor disagree about what is dark or opaque — the hand now, and where it was — on her free side,
    above HAND_ROWS, left of the face in the head rows; blobs only, dilated to take the wrist, feathered."""
    dark = lambda c: (c[:, :, :3].sum(axis=2) < 150) & (c[:, :, 3] > 200)
    opaque = lambda c: c[:, :, 3] > 127
    hand = (dark(cell) ^ dark(donor)) | (opaque(cell) ^ opaque(donor))
    hand[:, col0:] = False
    hand[:head_rows, face_left - 2:] = False
    hand[HAND_ROWS:] = False
    hand = ndi.binary_opening(hand, iterations=1)
    lab, k = ndi.label(hand)
    sizes = ndi.sum(hand, lab, range(1, k + 1))
    hand = np.isin(lab, [i + 1 for i, s in enumerate(sizes) if s >= 30])
    moving = ndi.binary_fill_holes(ndi.binary_dilation(hand, iterations=4))
    w = ndi.gaussian_filter(moving.astype(float), 1.5)[:, :, None]
    return straight(w * premul(cell) + (1 - w) * premul(donor))


donor = wave[WAVE_WAVES[0]]
for c in WAVE_WAVES[1:]:
    wave[c] = hold_hand(wave[c], donor)
for c in WAVE_REST:
    wave[c] = rest

WAVE_RISE = range(2, 8)           # the hand comes up: the cloak's lower edge may only lift
WAVE_FALL = range(16, 22)         # the hand goes down: it may only drop
LOW_ROW = 140                     # the lower cloak on her free side, below the raised arm


def lower_area(cell):
    """Coverage of the lower cloak on her free side (between LOW_ROW and the boots) — smaller as it lifts."""
    return cell[LOW_ROW:FEET_Y - 8, :col0, 3].astype(float).sum() / 255


def with_lower(cell, src):
    """`cell` with `src`'s lower cloak on her free side, the seam feathered over the rows above LOW_ROW — except
    around anything dark in either (the rising hand, and the rest pose's hanging hand, which would otherwise come
    back as a second hand), where the cell keeps its own pixels."""
    dark = lambda c: (c[:, :, :3].sum(axis=2) < 150) & (c[:, :, 3] > 200)
    w = np.clip((np.arange(H) - (LOW_ROW - 8)) / 10, 0, 1)[:, None] * (np.arange(W) < col0)[None, :]
    w = w * ~ndi.binary_dilation(dark(cell) | dark(src), iterations=4)
    w = ndi.gaussian_filter(w, 1.5)[:, :, None]
    return straight(w * premul(src) + (1 - w) * premul(cell))


def monotone_lower(cells, order, start, lifting):
    """Through a phase the lower cloak moves one way only. Measured exactly (alpha), the generator's rise dipped
    the hem ~2px before lifting it 6px, and its fall lifted it 1px before dropping it — the up-and-down bob Chanté
    saw. A cell that moves back keeps the lower cloak of the last cell that didn't."""
    kept = start
    for i in order:
        backwards = lower_area(cells[i]) > lower_area(kept) if lifting else lower_area(cells[i]) < lower_area(kept)
        if backwards:
            cells[i] = with_lower(cells[i], kept)
        else:
            kept = cells[i]
    return [round(float(lower_area(cells[i]) - lower_area(rest)), 1) for i in order]


print('lower cloak on the rise, px² from rest:', monotone_lower(wave, WAVE_RISE, rest, lifting=True))
print('lower cloak on the fall, px² from rest:', monotone_lower(wave, WAVE_FALL, donor, lifting=False))

# The foot play (2026-09-13, generated from art/prompts/lumi-foot-play.md, approved by Chanté): 24 in-betweens of
# another generation of the drawing — rest, the eyes lowering to the ground, her right boot (on the viewer's left)
# lifting and scuffing, the eyes rising, rest. Only the eyes and the moving boot are taken from it, onto the wave's
# first cell; everything else is `rest`, so the loop hands over to the breath and the wave without a swap.
FOOT_SRC = os.path.join(ROOT, 'art', 'lumi', 'lumi-foot-play.png')
FOOT_FRAMES = 24
FOOT_REST = [0, 1, *range(18, 24)]   # the rest pose, exactly (the sheet's eyes are back up from cell 18)
FOOT_EYES_DOWN = range(4, 16)        # the eyes down and still: all cell 5's
FOOT_EYES_UP = {17: 16}              # the look up was drawn twice alike: one cell's eyes
FOOT_PLAY = range(8, 16)             # the boot moves only here; elsewhere it is rest's
BOOT_TOP = FEET_Y - 34               # the boots and the hem's lower edge lie below this row


def eye_mask(cell):
    """The two eyes: the largest holes in the dark face, above the chin. Not cut at `head_rows` — the eyes lowered
    to the ground reach below it, and a mask cut there lost their bottom rows."""
    filled, dark = face(cell)
    holes = filled & ~dark
    holes[FEET_Y - FIGURE_H + int(FIGURE_H * 0.53):] = False   # the chin, as the head cut places it
    lab, k = ndi.label(holes)
    if not k: return holes
    sizes = ndi.sum(holes, lab, range(1, k + 1))
    return np.isin(lab, [i + 1 for i in np.argsort(sizes)[::-1][:2]])


def with_eyes(base, src):
    """`base` with `src`'s eyes: both cells' eyes and the glow around them, inside `base`'s face, feathered. The
    face is the same black in both, so where `base`'s eyes were, `src`'s face shows."""
    filled, _ = face(base)
    m = ndi.binary_dilation(eye_mask(base) | eye_mask(src), iterations=5) & ndi.binary_erosion(filled, iterations=2)
    w = ndi.gaussian_filter(m.astype(float), 1.2)[:, :, None]
    return straight(w * premul(src) + (1 - w) * premul(base))


def with_boot(base, src):
    """`base` with `src`'s moving boot: where the two disagree about what is dark or opaque, below BOOT_TOP on her
    free side — blobs only, dilated to take the boot's edge and where it was, feathered."""
    dark = lambda c: (c[:, :, :3].sum(axis=2) < 200) & (c[:, :, 3] > 200)
    opaque = lambda c: c[:, :, 3] > 127
    boot = (dark(src) ^ dark(base)) | (opaque(src) ^ opaque(base))
    boot[:BOOT_TOP] = False
    boot[:, col0:] = False
    boot = ndi.binary_opening(boot, iterations=1)
    lab, k = ndi.label(boot)
    sizes = ndi.sum(boot, lab, range(1, k + 1)) if k else []
    boot = np.isin(lab, [i + 1 for i, s in enumerate(sizes) if s >= 20])
    m = ndi.binary_fill_holes(ndi.binary_dilation(boot, iterations=3))
    w = ndi.gaussian_filter(m.astype(float), 1.2)[:, :, None]
    return straight(w * premul(src) + (1 - w) * premul(base))


foot_sheet = Sheet(FOOT_SRC, GROUND_BOX)
foot_boxes = [(r, b) for r, (y0, y1) in enumerate(foot_sheet.rows()) for b in foot_sheet.frames(y0, y1, COLS)]
assert len(foot_boxes) == FOOT_FRAMES, len(foot_boxes)
foot_matted = [(r, *foot_sheet.matte(b)) for r, b in foot_boxes]
foot_scale = {r: FIGURE_H / np.median([height(m) for rr, _, m in foot_matted if rr == r]) for r in sorted({r for r, _, _ in foot_matted})}
print('foot row scales', {r: round(float(s), 3) for r, s in foot_scale.items()})
foot_scaled = [scale(rgba, main, foot_scale[r]) for r, rgba, main in foot_matted]
drawn = [place(rgba, main, W, H, FEET_Y, cx=hood_right(main) - anchor) for rgba, main in foot_scaled]
held_foot = np.zeros((H, W))
held_foot[:head_rows] = 1          # the whole hood: it holds in this sheet, only the eyes move inside it
held_foot[head_rows:, col0:] = 1   # the ribbon's right side, the lantern and the other boot
foot_aligned = [align(c, rest, held_foot) for c in drawn]
print('foot overlap with the rest cell on the held parts, after aligning:', [round(float(o), 3) for _, o in foot_aligned])
drawn = [c for c, _ in foot_aligned]
foot = []
for i in range(FOOT_FRAMES):
    if i in FOOT_REST:
        foot.append(rest)
        continue
    cell = with_eyes(rest, drawn[5] if i in FOOT_EYES_DOWN else drawn[FOOT_EYES_UP.get(i, i)])
    if i in FOOT_PLAY:
        cell = with_boot(cell, drawn[i])
    foot.append(cell)

# The breath: the wave's first cell, stretched, so the two loops are one drawing.
rises = [BREATH_RISE * (1 - np.cos(2 * np.pi * i / BREATH_FRAMES)) / 2 for i in range(BREATH_FRAMES)]
print('breath rise per frame, px:', [round(r, 2) for r in rises])
KEEP = [None, 0.5, 0.2]   # open, half-shut, shut
lids = lambda cell, keep: cell if keep is None else eyes_shut(cell, keep)
# The wave keeps its eyes open: a blink during a 3 s gesture goes unseen, and its half-shut and shut
# rows would have tripled the sheet (917 KB against 244 KB before the wave). LumiSprite's
# LUMI_ROW_EYES says which eye rows each row of drawings has; the foot play keeps its eyes open too.
eye_rows = [
    [[breathe(lids(rest, keep), rise) for rise in rises] for keep in KEEP],
    [wave],
    [foot],
]
body = np.zeros((H * sum(len(rows) for rows in eye_rows), W * BODY_COLS, 4), dtype=np.uint8)
for r, cells in enumerate(row for rows in eye_rows for row in rows):
    for c, cell in enumerate(cells):
        body[r * H:(r + 1) * H, c * W:(c + 1) * W] = cell
Image.fromarray(body, 'RGBA').save(OUT_BODY, quality=90, method=6)
print('wrote', OUT_BODY, body.shape[1], 'x', body.shape[0], os.path.getsize(OUT_BODY), 'bytes')

sheet = Sheet(SRC, GROUND_BOX)
heads = np.zeros((HEAD_CELL, HEAD_CELL * len(HEADS), 4), dtype=np.uint8)
for i, (name, at, eyes) in enumerate(HEADS):
    heads[:, i * HEAD_CELL:(i + 1) * HEAD_CELL] = head_cell(*sheet.matte(sheet.cell(*at)), eyes)
Image.fromarray(heads, 'RGBA').save(OUT_HEADS, optimize=True)
print('wrote', OUT_HEADS, heads.shape[1], 'x', heads.shape[0], os.path.getsize(OUT_HEADS), 'bytes')

if DEBUG:
    # Everything on the app's paper, to look at: the heads at 3×, the body at 1× (it is 3840 wide).
    paper = (246, 241, 232)
    def on_paper(a, k=3):
        im = Image.new('RGBA', (a.shape[1], a.shape[0]), paper + (255,))
        im.alpha_composite(Image.fromarray(a, 'RGBA'))
        return im.resize((im.width * k, im.height * k), Image.NEAREST)
    on_paper(body, 1).save(os.path.join(DEBUG, 'cut-body.png'))
    on_paper(heads).save(os.path.join(DEBUG, 'cut-heads.png'))
    print('debug strips in', DEBUG)
