/**
 * Day plans: the persisted path through today. Generated by core/ai/plan.ts
 * (model proposes, code guards), advanced here by code when Right now is done.
 */
import { and, desc, eq } from "drizzle-orm";
import { type Db } from "@/db/client";
import { dayPlans, type DayPlanJson, type DayPlanRow, type Intention, type PlanReason } from "@/db/schema";
import { appendEvent } from "./events";

export async function getPlanForDate(db: Db, userId: string, localDate: string): Promise<DayPlanRow | undefined> {
  const [row] = await db
    .select()
    .from(dayPlans)
    .where(and(eq(dayPlans.userId, userId), eq(dayPlans.localDate, localDate)))
    .orderBy(desc(dayPlans.generatedAt))
    .limit(1);
  return row;
}

export async function savePlan(db: Db, userId: string, localDate: string, plan: DayPlanJson, reason: PlanReason, capacity?: string): Promise<DayPlanRow> {
  const [row] = await db.insert(dayPlans).values({ userId, localDate, plan, reason, capacity: capacity ?? null }).returning();
  await appendEvent(db, { userId, type: reason === "advanced" ? "plan.advanced" : "plan.generated", subjectType: "user", subjectId: userId, payload: { reason, localDate, rightNow: plan.rightNow?.intentionId ?? null } });
  return row;
}

/**
 * Pure: the path after an intention leaves it (done or dropped). Right now
 * becomes the next After-that; nothing is regenerated. Tested.
 */
export function advancePlan(plan: DayPlanJson, goneId: string, fallbackFirstStep = "Pick it up where it opens."): DayPlanJson {
  const afterThat = plan.afterThat.filter((a) => a.intentionId !== goneId);
  const later = plan.later.filter((l) => l.intentionId !== goneId);
  if (plan.rightNow?.intentionId !== goneId) return { ...plan, afterThat, later };
  const next = afterThat.shift();
  return {
    ...plan,
    rightNow: next ? { intentionId: next.intentionId, firstStep: fallbackFirstStep } : null,
    afterThat,
    later,
  };
}

/** Pure: drop ids that are no longer open (completed elsewhere, dropped) so the page never shows a ghost. */
export function prunePlan(plan: DayPlanJson, open: Pick<Intention, "id">[]): DayPlanJson {
  const ids = new Set(open.map((i) => i.id));
  let p: DayPlanJson = { ...plan, afterThat: plan.afterThat.filter((a) => ids.has(a.intentionId)), later: plan.later.filter((l) => ids.has(l.intentionId)) };
  if (p.rightNow && !ids.has(p.rightNow.intentionId)) p = advancePlan(p, p.rightNow.intentionId);
  return p;
}
